### ISSUE TITLE
bug, non existing folder in iterdir

### ISSUE THREAD

**Issue by hannesdelbeke** [plugget/plugget-qt#9]
```
Traceback (most recent call last):
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\modules\plugget_qt\__init__.py", line 140, in search_packages
    packages = cmd.search(self.search_field.text())
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\modules\plugget\commands\__init__.py", line 159, in search
    manifest_paths = _discover_manifest_paths(name=name, search_paths=search_paths)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\modules\plugget\commands\__init__.py", line 173, in _discover_manifest_paths
    package_dirs = [package_dir for package_dir in app_path.iterdir() if package_dir.is_dir()]
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\modules\plugget\commands\__init__.py", line 173, in <listcomp>
    package_dirs = [package_dir for package_dir in app_path.iterdir() if package_dir.is_dir()]
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\pathlib.py", line 1015, in iterdir
    for name in self._accessor.listdir(self):
```

strange since we check if folder exists before iter
```python

def _discover_manifest_paths(search_paths, name=None):
    """search for manifest files"""
    manifest_paths = []  # get the manifests
    for app_path in search_paths:  # iter app folders
        if not app_path.exists():
            continue
        package_dirs = [package_dir for package_dir in app_path.iterdir() if package_dir.is_dir()]
        for package_dir in package_dirs:  # iter package folders
            for manifest_path in package_dir.glob("*.json"):  # iter manifests
                source_name = package_dir.name  # this checks for manifest name, not name in package todo
                if name is None or name.lower() in source_name.lower():  # todo we search manifest file name, instead of name in the package
                    manifest_paths.append(manifest_path)
    return manifest_paths
```

**Comment by hannesdelbeke** [comment]
possibly related to cached local version.

**Comment by hannesdelbeke** [comment]
fixed bug in [detect_app](https://github.com/hannesdelbeke/detect-app)
